# Generated by Django 5.0.6 on 2024-06-13 10:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("app1", "0002_delete_joindetails"),
    ]

    operations = [
        migrations.CreateModel(
            name="JoinDetails",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("email", models.EmailField(max_length=254)),
                ("join_date", models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
