# Generated by Django 5.0.2 on 2024-06-13 12:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0003_joindetails'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='courselinks',
            name='flag',
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='flag',
            field=models.IntegerField(choices=[(-1, '-1'), (0, '0'), (1, '1'), (2, '2')], default=0),
        ),
    ]
