# Generated by Django 5.0.2 on 2024-06-27 05:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app1', '0005_contact_java_batch_products_of_the_company_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Java_Batch',
        ),
        migrations.DeleteModel(
            name='Products_of_the_company',
        ),
        migrations.DeleteModel(
            name='Python_Batch',
        ),
        migrations.DeleteModel(
            name='Record',
        ),
        migrations.DeleteModel(
            name='Record_java',
        ),
        migrations.DeleteModel(
            name='WhatsAppLink_java',
        ),
        migrations.DeleteModel(
            name='WhatsAppLink_python',
        ),
    ]
